version: '3.9'
services:
  db:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: movie
    volumes:
      - './db:/var/lib/mysql'
    restart: always
    networks:
      - backend
    command:
      "--log_bin_trust_function_creators=1"
  app:
    image: 'adoptopenjdk/openjdk11'
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/movie?autoReconnect=true&failOverReadOnly=false&maxReconnects=10&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    build:
      context: "./"
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    networks:
      - backend
volumes:
  db:
    driver: local
networks:
  backend:
    driver: bridge