version: '3.9'
services:
  db:
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=movie
    ports:
      - "3308:3306"
    volumes:
      - 'db:/var/lib/mysql'
    restart: always
    networks:
      - backend
  app:
    image: 'adoptopenjdk/openjdk11'
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/movie?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    networks:
      - backend
volumes:
  db:
networks:
  backend: